version: "0.5"

log_location: ./dist/process-compose.log

processes:
  build:
    command: "yarn build:watch --watch=forever"
  ff-bot:
    command: "yarn start:watch"
    availability:
      restart: "always"
    readiness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/command/health"
        port: 3001
    depends_on:
      build:
      groupmesim:
  groupmesim:
    command: "yarn start:groupmesim"
    availability:
      restart: "always"
    shutdown:
      command: "docker-compose stop groupmesim"
  ngrok:
    command: "yarn start:ngrok"
    availability:
      restart: "always"
    depends_on:
      ff-bot:
        condition: process_healthy
